### ISSUE TITLE
Job needs to add parameter setting function

### ISSUE THREAD

**Issue by harbby** [harbby/sylph#2]
Similar to spark:
```bash
--executor-memory 2g
--executor-cores 2
--num-executors 2
--driver-memory 2g
--driver-cores 2
```

**Comment by harbby** [comment]
Currently support flink runner parameter settings first
They look like this:
```yaml
type: "StreamSql"
config:
  taskManagerMemoryMb: 1024
  taskManagerCount: 2
  taskManagerSlots: 2
  jobManagerMemoryMb: 1024
  parallelism: 4
  queue: "default"
  appTags:
  - "sylph"
  - "flink"
```
